# Done to increase the memory available to Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=26.2
loom_version=1.17-SNAPSHOT
architectury_version=3.5-SNAPSHOT

# Mod Properties
mod_version=0.1.8
maven_group=org.minimalmenu
archive_name=minimenu

# Dependencies
shadow_version=9.6.1
neoforge_version=26.2.0.75
fabric_loader_version=0.19.5
fabric_api_version=0.159.0+26.2
yacl_version=3.9.6

# Development Dependencies
modmenu_version=20.0.1